# Generated by Django 3.2.21 on 2023-09-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the category name', max_length=200, verbose_name='category name')),
                ('slug', models.SlugField(help_text='the slug is here', unique=True, verbose_name='category slug')),
                ('image', models.ImageField(help_text='upload the category image', upload_to='images/categories/', verbose_name='category image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the subcategory name', max_length=200, verbose_name='subcategory name')),
                ('slug', models.SlugField(help_text='the slug is here', unique=True, verbose_name='subcategory slug')),
                ('image', models.ImageField(help_text='upload the subcategory image', upload_to='images/subcategories/', verbose_name='subcategory image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='store.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Subcategory',
                'verbose_name_plural': 'Subcategories',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_goods_number', models.IntegerField(default=0, help_text='number of goods in a cart here', null=True, verbose_name='number of goods in a cart')),
                ('total_sum', models.DecimalField(decimal_places=2, default=0, help_text='total price of goods in a cart here', max_digits=8, null=True, verbose_name='total price of goods in a cart')),
                ('customer', models.ForeignKey(help_text='customer name here', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='enter the product name', max_length=200, verbose_name='product name')),
                ('slug', models.SlugField(help_text='the slug is here', unique=True, verbose_name='product slug')),
                ('price', models.DecimalField(decimal_places=2, help_text='enter the product price', max_digits=5, null=True, verbose_name='product price')),
                ('big_image', models.ImageField(help_text='upload the product image', upload_to='images/products/', verbose_name='big product image')),
                ('middle_sized_image', models.ImageField(help_text='upload the product image', upload_to='images/products/', verbose_name='middle-sized product image')),
                ('small_image', models.ImageField(help_text='upload the product image', upload_to='images/products/', verbose_name='small product image')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='store.subcategory', verbose_name='subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GoodInCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_number', models.IntegerField(help_text='number of a certain product', null=True, verbose_name='number of a certain product')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='here product price in a cart', max_digits=8, null=True, verbose_name='product price in a cart')),
                ('cart', models.ForeignKey(help_text='cart with goods here', on_delete=django.db.models.deletion.CASCADE, related_name='cart_goods', to='store.shoppingcart', verbose_name='cart with goods')),
                ('product', models.ForeignKey(help_text='product in a cart here', null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='product in a cart')),
            ],
            options={
                'verbose_name': 'Goods in cart',
                'verbose_name_plural': 'Goods in cart',
            },
        ),
    ]
